### PR TITLE
Fixed README inconsistencies

### PR DESCRIPTION
**Pull request by Sirneij**
Added some fixes to the README.md

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @samsucik will take a look at it as soon as possible ✨

**Review by samsucik — CHANGES_REQUESTED** [review]
Thanks a lot @Sirneij! Before we go further, could you, please, add a mention of the rules file too? Just so the description of the data directory is complete.

**Comment by Sirneij** [comment]
Alright... I am requesting for a review

**Review by samsucik — APPROVED** [review]
Thanks a lot @Sirneij 🙂

**Pull request merged**
